---
title: "My Iris Dashboard"
author: "Ikansh Mahajan"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    source_code: embed
runtime: shiny
---

```{css}
.dashboard-page .section, 
.dashboard-page .section .chart-wrapper, 
.box, 
.box-body, 
.chart-stage {
  overflow: visible !important;
}

.selectize-control, 
.selectize-dropdown {
  z-index: 99999 !important;
}
```

```{r setup, include=FALSE}
library(dplyr)
library(flexdashboard)
library(ggplot2)
library(shiny)

data(iris)
df <- iris
```

## \## Row {data-height="200"}

### Number of clusters

```{r}
uiOutput("cluster_slider")
```

```{r, context="server"}
output$cluster_slider <- renderUI({
  req(input$feat.x, input$feat.y)

  max_k <- nrow(unique(df[, c(input$feat.x, input$feat.y)]))

  sliderInput(
    "n.cluster",
    label = NULL,
    min = 1,
    max = max_k,
    value = min(3, max_k),
    step = 1,
    ticks = FALSE
  )
})
```

### Number of iterations

```{r}
sliderInput(
    "n.iter",
    label = NULL,
    min = 1,
    max = 300,
    value = 20,
    ticks = FALSE
)
```

### X feature

```{r}
selectizeInput(
    inputId = "feat.x",
    label = NULL,
    choices = names(iris)[1:4],
    selected = "Sepal.Length"
)
```

### Y feature

```{r}
selectizeInput(
    inputId = "feat.y",
    label = NULL,
    choices = names(iris)[1:4],
    selected = "Sepal.Width"
)
```

```{r, context="server"}
observeEvent(input$feat.x, {
  updateSelectizeInput(
    session,
    "feat.y",
    choices = setdiff(names(iris)[1:4], input$feat.x)
  )
})
```

## \## Row {data-height="500"}

### Species clusters

```{r}
renderPlot({
  req(input$feat.x, input$feat.y, iris)
  
  ggplot(iris) +
    aes(
      x = .data[[input$feat.x]],
      y = .data[[input$feat.y]],
      color = .data[["Species"]]
    ) +
    geom_point() +
    theme_minimal() +
    theme(
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      legend.title = element_blank(),
      legend.justification = c(1, 1)
    )
})
```

### k-means clusters

```{r}
km_reactive <- reactive({
  req(input$feat.x, input$feat.y, input$n.cluster, input$n.iter, iris, df)
  
  kmeans(
    df[, c(input$feat.x, input$feat.y)],
    centers = input$n.cluster,
    iter.max = input$n.iter
  )
})

df_with_cluster <- reactive({
  req(km_reactive, df)
  
  km <- km_reactive()
  df$cluster <<- factor(km$cluster)
  df
})

renderPlot({
  req(input$feat.x, input$feat.y, km_reactive, df_with_cluster)
    
  df_with_cluster()   # Adds cluster column to data frame
  
  ggplot(df) +
    aes(
      x = .data[[input$feat.x]],
      y = .data[[input$feat.y]],
      color = cluster
    ) +
    geom_point() +
    theme_minimal() +
    theme(
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      legend.title = element_blank(),
      legend.justification = c(1, 1)
    )
})
```

## \## Row {data-height="300"}

### Iris data

```{r}

```
